import type { ChartView, SummaryView, TableView, ViewDiagnostic, ViewSection, ViewSpec } from "../presentation.js";

export interface RenderElement { textContent: string | null; readonly childNodes: readonly RenderNode[]; appendChild(child: RenderNode): RenderNode; setAttribute(name: string, value: string): void; }
export interface RenderDocument { createElement(name: string): RenderElement; createElementNS(namespace: string, name: string): RenderElement; }
export interface RenderHost extends RenderElement { replaceChildren(...children: RenderNode[]): void; }
export type RenderNode = RenderElement;
export interface RenderResult { readonly renderedSections: number; readonly errors: readonly ViewDiagnostic[]; readonly teardown: () => void; }
const SVG_NAMESPACE = "http://www.w3.org/2000/svg";
function element(document: RenderDocument, name: string, text?: string): RenderElement { const node = document.createElement(name); if (text !== undefined) node.textContent = text; return node; }
function svg(document: RenderDocument, name: string): RenderElement { return document.createElementNS(SVG_NAMESPACE, name); }
function renderDiagnostics(document: RenderDocument, diagnostics: readonly ViewDiagnostic[]): RenderElement { const list = element(document, "ul"); for (const diagnostic of diagnostics) { const item = element(document, "li", diagnostic.message); item.setAttribute("data-severity", diagnostic.severity); list.appendChild(item); } return list; }
function renderSummary(document: RenderDocument, view: SummaryView): RenderElement { const section = element(document, "section"); section.appendChild(element(document, "h2", view.title)); for (const item of view.items) { const paragraph = element(document, "p"); paragraph.appendChild(element(document, "strong", `${item.label}: `)); paragraph.appendChild(element(document, "span", item.value)); section.appendChild(paragraph); } return section; }
function renderTable(document: RenderDocument, view: TableView): RenderElement { const section = element(document, "section"); section.appendChild(element(document, "h2", view.title)); const table = element(document, "table"); const header = element(document, "tr"); for (const column of view.columns) header.appendChild(element(document, "th", column)); table.appendChild(header); for (const row of view.rows) { const tableRow = element(document, "tr"); for (const value of row) tableRow.appendChild(element(document, "td", value)); table.appendChild(tableRow); } section.appendChild(table); return section; }
function renderChart(document: RenderDocument, view: ChartView): RenderElement { const section = element(document, "section"); section.appendChild(element(document, "h2", view.title)); const chart = svg(document, "svg"); chart.setAttribute("role", "img"); chart.setAttribute("aria-label", `${view.title}${view.unit === "" ? "" : ` (${view.unit})`}`); chart.setAttribute("viewBox", "0 0 100 100"); const maximum = Math.max(...view.values, 0); view.values.forEach((value, index) => { const bar = svg(document, "rect"); bar.setAttribute("x", String(index * (100 / Math.max(view.values.length, 1)))); bar.setAttribute("y", String(maximum === 0 ? 100 : 100 - (value / maximum) * 90)); bar.setAttribute("width", String(90 / Math.max(view.values.length, 1))); bar.setAttribute("height", String(maximum === 0 ? 0 : (value / maximum) * 90)); bar.setAttribute("data-label", view.labels[index] ?? ""); chart.appendChild(bar); }); section.appendChild(chart); return section; }
function renderSection(document: RenderDocument, section: ViewSection): RenderElement { if (section.kind === "summary") return renderSummary(document, section); if (section.kind === "table") return renderTable(document, section); return renderChart(document, section); }
/** Renders a ViewSpec using safe text/attribute APIs. The host is replaced only after the complete update is assembled. */
export function renderViewSpec(document: RenderDocument, host: RenderHost, spec: ViewSpec): RenderResult { const next = document.createElement("div"); const errors: ViewDiagnostic[] = []; next.appendChild(element(document, "h1", spec.title)); next.appendChild(renderDiagnostics(document, spec.diagnostics)); let renderedSections = 0; for (const section of spec.sections) { try { next.appendChild(renderSection(document, section)); renderedSections += 1; } catch (error) { errors.push({ severity: "error", message: error instanceof Error ? error.message : "Unable to render section." }); } } if (errors.length === 0) host.replaceChildren(...next.childNodes); return { renderedSections, errors, teardown: () => host.replaceChildren() }; }
