import { createHash } from "node:crypto";
import { inflateRawSync } from "node:zlib";

export const ASSET_ROOT = "schemas";
export const PROVENANCE_FILE = "provenance.json";
export const LICENSE_FILE = "LICENSE";
export const GENERATED_TS_FILE = "src/assets/provenance.ts";

const ASSET_ENTRY = /^(schema|registry)\/[A-Za-z0-9][A-Za-z0-9._-]*\.json$/;
const REPOSITORY = /^[A-Za-z0-9][A-Za-z0-9-]*\/(?!\.\.?$)[A-Za-z0-9_.-]+$/;
const TAG = /^v\d+\.\d+\.\d+$/;
const COMMIT = /^[0-9a-f]{40}$/;
const SHA256 = /^[0-9a-f]{64}$/;
const ARTIFACT_NAME = /^[A-Za-z0-9][A-Za-z0-9._-]*\.jar$/;

export function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

export function artifactUrl(pin) {
  return `https://github.com/${pin.repository}/releases/download/${pin.tag}/${pin.artifact.name}`;
}

export function licenseUrl(pin) {
  return `https://raw.githubusercontent.com/${pin.repository}/${pin.commit}/${LICENSE_FILE}`;
}

/**
 * Validates the human-maintained pin fields of `schemas/provenance.json`.
 * Derived fields (URLs and file digests) are regenerated by the sync script.
 */
export function validatePin(pin) {
  const problems = [];
  if (!REPOSITORY.test(pin?.repository ?? "")) problems.push("repository must be <owner>/<name>");
  if (!TAG.test(pin?.tag ?? "")) problems.push("tag must be v<major>.<minor>.<patch>");
  if (!COMMIT.test(pin?.commit ?? "")) problems.push("commit must be a full 40-character SHA");
  if (!ARTIFACT_NAME.test(pin?.artifact?.name ?? "")) problems.push("artifact.name must be a .jar file name");
  if (!SHA256.test(pin?.artifact?.sha256 ?? "")) problems.push("artifact.sha256 must be a lowercase hex SHA-256");
  if (problems.length > 0) {
    throw new Error(`Invalid schema asset pin:\n  ${problems.join("\n  ")}`);
  }
}

/**
 * Reads the file entries of a (non-ZIP64) zip/jar archive into a map of
 * entry name to uncompressed bytes.
 */
export function readZipEntries(archive) {
  const buf = Buffer.from(archive.buffer, archive.byteOffset, archive.byteLength);
  const eocd = findEndOfCentralDirectory(buf);
  const count = buf.readUInt16LE(eocd + 10);
  const directoryOffset = buf.readUInt32LE(eocd + 16);
  if (directoryOffset === 0xffffffff || count === 0xffff) {
    throw new Error("ZIP64 archives are not supported");
  }

  const entries = new Map();
  let p = directoryOffset;
  for (let i = 0; i < count; i++) {
    if (p + 46 > buf.length || buf.readUInt32LE(p) !== 0x02014b50) {
      throw new Error(`Corrupt zip central directory at offset ${p}`);
    }
    const flags = buf.readUInt16LE(p + 8);
    const method = buf.readUInt16LE(p + 10);
    const compressedSize = buf.readUInt32LE(p + 20);
    const size = buf.readUInt32LE(p + 24);
    const nameLength = buf.readUInt16LE(p + 28);
    const extraLength = buf.readUInt16LE(p + 30);
    const commentLength = buf.readUInt16LE(p + 32);
    const localOffset = buf.readUInt32LE(p + 42);
    const name = buf.toString("utf8", p + 46, p + 46 + nameLength);
    p += 46 + nameLength + extraLength + commentLength;

    if (name.endsWith("/")) continue;
    if (flags & 0x1) throw new Error(`Encrypted zip entry is not supported: ${name}`);
    if (entries.has(name)) throw new Error(`Duplicate zip entry: ${name}`);
    if (localOffset + 30 > buf.length || buf.readUInt32LE(localOffset) !== 0x04034b50) {
      throw new Error(`Corrupt zip local header for ${name}`);
    }

    const dataStart = localOffset + 30 + buf.readUInt16LE(localOffset + 26) + buf.readUInt16LE(localOffset + 28);
    if (dataStart + compressedSize > buf.length) {
      throw new Error(`Truncated zip entry: ${name}`);
    }
    const data = buf.subarray(dataStart, dataStart + compressedSize);
    let content;
    if (method === 0) content = Buffer.from(data);
    else if (method === 8) content = inflateRawSync(data);
    else throw new Error(`Unsupported zip compression method ${method} for ${name}`);
    if (content.length !== size) {
      throw new Error(`Size mismatch for zip entry ${name}: expected ${size}, got ${content.length}`);
    }
    entries.set(name, content);
  }
  return entries;
}

function findEndOfCentralDirectory(buf) {
  const minOffset = Math.max(0, buf.length - 22 - 0xffff);
  for (let i = buf.length - 22; i >= minOffset; i--) {
    if (buf.readUInt32LE(i) === 0x06054b50) return i;
  }
  throw new Error("Not a zip archive: end of central directory not found");
}

/**
 * Selects the canonical `schema/*.json` and `registry/*.json` entries of the
 * released artifact. Anything else (manifests, nested paths) is ignored.
 */
export function selectAssetEntries(entries) {
  const selected = new Map();
  for (const [name, content] of entries) {
    if (ASSET_ENTRY.test(name)) selected.set(name, content);
  }
  if (![...selected.keys()].some((name) => name.startsWith("schema/"))) {
    throw new Error("Release artifact does not contain any schema/*.json entries");
  }
  if (![...selected.keys()].some((name) => name.startsWith("registry/"))) {
    throw new Error("Release artifact does not contain any registry/*.json entries");
  }
  return new Map([...selected].sort(([a], [b]) => compareStrings(a, b)));
}

export function verifyArtifactDigest(pin, bytes) {
  const actual = sha256(bytes);
  if (actual !== pin.artifact.sha256) {
    throw new Error(
      `Release artifact digest mismatch for ${pin.artifact.name}: expected ${pin.artifact.sha256}, got ${actual}`,
    );
  }
}

export function buildProvenance(pin, assets, license) {
  return {
    repository: pin.repository,
    tag: pin.tag,
    commit: pin.commit,
    artifact: {
      name: pin.artifact.name,
      url: artifactUrl(pin),
      sha256: pin.artifact.sha256,
    },
    license: {
      path: LICENSE_FILE,
      url: licenseUrl(pin),
      sha256: sha256(license),
    },
    files: [...assets].map(([path, content]) => ({ path, sha256: sha256(content) })),
  };
}

export function renderProvenanceJson(provenance) {
  return `${JSON.stringify(provenance, null, 2)}\n`;
}

export function renderProvenanceModule(provenance) {
  return [
    "// Generated by scripts/sync-schema-assets.mjs from schemas/provenance.json. Do not edit.",
    'import type { SchemaAssetProvenance } from "./types.js";',
    "",
    `export const SCHEMA_ASSETS: SchemaAssetProvenance = ${JSON.stringify(provenance, null, 2)};`,
    "",
  ].join("\n");
}

function compareStrings(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}
